codeSystems:
  'http://snomed.info/sct': SNOMED CT
  'http://hl7.org/fhir/sid/icd-10-cm': ICD-10 CM

excludeElement: [
  'DeviceRequest.modifierExtension',
  'DeviceRequest.modifierExtension:doNotPerform',
  'Task.output.value[x]',
  'Encounter.reasonReference',
  'Claim.extension:encounter']